##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,4]])

[10 30 50]


You can do this fancy indexing in 2D Matrix aswell

In [ ]:
arr = np.arange(1,13).reshape(3,4)
print(arr)
print()
print(arr[[0,2,2],[0,1,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 1 10 12]


##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([18,55,45,25,12,8])
print(arr>20)
print(np.where(arr>20))
print(np.where(arr>20,arr,0))


[False  True  True  True False False]
(array([1, 2, 3]),)
[ 0 55 45 25  0  0]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
arr = np.array([25,12,45,8,10,50])
print(np.sort(arr))

[ 8 10 12 25 45 50]


In [ ]:
print(np.argsort(arr))

[3 4 1 0 2 5]


##Concatenation & Stacking

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(np.vstack([A,B]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(np.vstack([B,A]))

[[5 6]
 [7 8]
 [1 2]
 [3 4]]


In [ ]:
print(np.hstack([A,B]))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.hstack([B,A]))

[[5 6 1 2]
 [7 8 3 4]]
