# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [6]:
arr = np.array(['1',2,3,4,5])
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')

Lets create a matrix using list

In [7]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Now lets see how matlix looks like using numpy arrays

In [8]:
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [10]:
np.zeros([5,8])

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones([8,9])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(4,5)

array([[0.47997176, 0.17507974, 0.02800387, 0.28846518, 0.63151238],
       [0.76090648, 0.78249841, 0.08647813, 0.07851815, 0.12286264],
       [0.48964599, 0.297068  , 0.63631789, 0.87199285, 0.56101353],
       [0.48392058, 0.35366237, 0.13142225, 0.02306139, 0.84380549]])

In [19]:
np.random.randint(1,100,(6,10))

array([[17, 46,  8, 12, 12, 82, 93, 89, 61, 46],
       [ 3, 37, 30, 55, 95, 67, 48, 66, 70, 12],
       [94,  4, 70,  2, 21, 80, 49, 68, 19, 58],
       [ 8, 11, 17, 58, 89, 14, 71, 24, 67, 32],
       [66, 61, 81, 34, 41, 95, 30, 67, 63, 14],
       [ 9, 31, 34, 34, 66, 95, 18, 50, 43, 46]])

In [23]:
arr = np.random.randn(5,4)
arr

array([[ 0.17512707,  1.25698308,  0.48179123, -0.10646122],
       [ 1.0814585 ,  0.68058244,  1.11390242, -1.52280362],
       [-1.23302554, -0.25531373, -1.11506159,  0.16381185],
       [-0.19819398,  0.22351789,  1.2751481 , -1.29408934],
       [ 2.13816766,  1.51779896, -0.52383528, -1.57299718]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution

In [24]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a1*a2

array([ 4, 10, 18])