##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [10]:
import numpy as np

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [13]:
arr =  np.array([1,2,3,4,5])
print(arr)
print(arr[0])
print(arr[3])
print(arr[-4])

[1 2 3 4 5]
1
4
2


Now lets see the 2D indexing aswell

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print(arr[0])

[1 2 3]


In [20]:
print(arr[0,2])

3


Now we can also do the slicing lets see the **slicing in 1D**

In [31]:
arr =  np.array([1,2,3,4,5])
arr
arr[:3]

array([1, 2, 3])

1D slicing was really easy now lets see the **slicing in 2D**

In [29]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print()
print(arr[1:,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5]
 [7 8]]


There is one more thing known as **Boolean indexing**

In [35]:
arr =  np.array([1,2,3,4,5])
print(arr>2)
print(arr[arr>2])

[False False  True  True  True]
[3 4 5]


In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr>3)
print(arr[arr>3])

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [41]:
a = np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [42]:
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
