##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [3]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a//b)
print(a*b)

[11 22 33 44]
[ 9 18 27 36]
[10 10 10 10]
[ 10  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [4]:
a = np.array([1,2,3,4,5])
print(a*2)

[ 2  4  6  8 10]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [6]:
a = np.array([[1,2,3],[4,5,6]])
print(a*5)


[[ 5 10 15]
 [20 25 30]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [13]:
arr = np.array([4,8,12,16,25,20])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))

[ 4  8 12 16 25 20]
85
14.166666666666666
14.0
25
4
7.080881928749334
50.138888888888886


You can also do the axis based operations row-Wise and Colum-wise

In [14]:
data =  np.arange(1,10).reshape(3,3)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(np.sum(data,axis=1))
print(np.sum(data,axis=0))
print(np.mean(data,axis=0))
print(np.mean(data,axis=1))

[ 6 15 24]
[12 15 18]
[4. 5. 6.]
[2. 5. 8.]
